"""NTFS constants and magic numbers."""

# Sector and cluster sizes
SECTOR_SIZE = 512
CLUSTER_SIZE = 4096  # 8 sectors per cluster
SECTORS_PER_CLUSTER = CLUSTER_SIZE // SECTOR_SIZE

# MFT record size
MFT_RECORD_SIZE = 1024

# MFT system record numbers
MFT_RECORD_MFT = 0
MFT_RECORD_MFTMIRR = 1
MFT_RECORD_LOGFILE = 2
MFT_RECORD_VOLUME = 3
MFT_RECORD_ATTRDEF = 4
MFT_RECORD_ROOT = 5
MFT_RECORD_BITMAP = 6
MFT_RECORD_BOOT = 7
MFT_RECORD_BADCLUS = 8
MFT_RECORD_SECURE = 9
MFT_RECORD_UPCASE = 10
MFT_RECORD_EXTEND = 11
MFT_RECORD_RESERVED_START = 12
MFT_RECORD_RESERVED_END = 15
MFT_RECORD_USER_START = 16

# Attribute types
ATTR_STANDARD_INFORMATION = 0x10
ATTR_ATTRIBUTE_LIST = 0x20
ATTR_FILE_NAME = 0x30
ATTR_OBJECT_ID = 0x40
ATTR_SECURITY_DESCRIPTOR = 0x50
ATTR_VOLUME_NAME = 0x60
ATTR_VOLUME_INFORMATION = 0x70
ATTR_DATA = 0x80
ATTR_INDEX_ROOT = 0x90
ATTR_INDEX_ALLOCATION = 0xA0
ATTR_BITMAP = 0xB0
ATTR_REPARSE_POINT = 0xC0
ATTR_EA_INFORMATION = 0xD0
ATTR_EA = 0xE0
ATTR_END = 0xFFFFFFFF

# MFT record flags
MFT_RECORD_IN_USE = 0x01
MFT_RECORD_IS_DIRECTORY = 0x02

# File attribute flags (for $STANDARD_INFORMATION)
FILE_ATTR_READONLY = 0x0001
FILE_ATTR_HIDDEN = 0x0002
FILE_ATTR_SYSTEM = 0x0004
FILE_ATTR_DIRECTORY = 0x0010
FILE_ATTR_ARCHIVE = 0x0020
FILE_ATTR_NORMAL = 0x0080

# Filename namespace
FILENAME_POSIX = 0
FILENAME_WIN32 = 1
FILENAME_DOS = 2
FILENAME_WIN32_AND_DOS = 3

# Index entry flags
INDEX_ENTRY_NODE = 0x01
INDEX_ENTRY_END = 0x02

# Volume information flags
VOLUME_IS_DIRTY = 0x0001

# NTFS version
NTFS_VERSION_MAJOR = 3
NTFS_VERSION_MINOR = 1

# Magic signatures
NTFS_SIGNATURE = b'NTFS    '
FILE_SIGNATURE = b'FILE'
INDX_SIGNATURE = b'INDX'
